- hosts: webserver
  user: ubuntu
  sudo: True
  roles:
    - nginx
  vars:
      serverListenPort: "8090"
      serverListenAddress: "0.0.0.0"
      nginxProxyToAddress: "0.0.0.0"
      nginxProxyToPort: "8090"
      wwwUID: "ubuntu"
      wwwGID: "ubuntu"
      deploymentBranch: "master"